name: logs

on:
  workflow_dispatch:
    branches:
      - main

jobs:
    logs:
        runs-on: ubuntu-latest
        steps:

        - name: Checkout project sources
          uses: actions/checkout@v3

        - name: Write decryption key
          run: |
            echo "${{ secrets.CRYPT_KEY }}" > crypt.base64 
            base64 -d crypt.base64 | gpg --batch --yes --passphrase-fd 0 --decrypt --output grpg.files/application-decrypt.yml grpg.files/application.yml.gpg
            cat grpg.files/application-decrypt.yml




