name: logs

on:
  workflow_dispatch:
    branches:
      - main

jobs:
    logs:
        runs-on: ubuntu-latest
        steps:

        - name: Checkout project sources
          uses: actions/checkout@v3

        - name: Write decryption key
          run: |
            echo "${{ secrets.CRYPT_KEY }}" | base64 --decode > crypt.key
          env:
            GIT_CRYPT_KEY: ${{ secrets.CRYPT_KEY }}

        - name: print key
          run: |
            cat crypt.key
          env:
            GIT_CRYPT_KEY: ${{ secrets.GIT_CRYPT_KEY }}


